# This is a file for using Docker with this project locally

version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rkoron/at-sea
    command:
      sh -c "rm -f tmp/pids/server.pid && SECRET_KEY_BASE=production_test_key
      rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres@db"
