FROM node:7.8.0

WORKDIR /app

# Install all dependencies of the current project.
COPY package.json package.json
COPY webpack.config.js .
RUN npm install

# Copy all local files into the image.
COPY /frontend .
EXPOSE 3000
CMD npm start
