version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.rails
    image: rkoron/atsea-rails
    command: puma
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres@db
    depends_on:
      - db
  frontend:
      build: 
        context: .
        dockerfile: Dockerfile.react
      image: rkoron/atsea-react
      volumes:
        - '.:/usr/src/app'
        - '/usr/src/app/node_modules'
      ports:
        - "80:3000"
      environment:
        - NODE_ENV=development 
  
