branch-defaults:
  master:
    environment: AtSea2-dev
    group_suffix: null
global:
  application_name: AtSea2
  branch: null
  default_ec2_keyname: null
  default_platform: Multi-container Docker 18.06.1-ce (Generic)
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
